### ISSUE TITLE
Tasks Q4

### ISSUE THREAD

**Issue by triplezeta** [shiptest-ss13/Shiptest#350]
# Shiptest Q4 Tasks 

## Backend

- [x] Job Refactor #353 
- [ ] Overmap Rework #209
- [ ] Prefs Refactor (And TGUI Preferences)
- [ ] Events
- [ ] Multiple ruins per planetoid, split ruin pools into major and minor #357 

## Frontend

- [x] Ship OOC notes #436
- [x] Landing on Empty Space #376 
- [ ] Interdictions/Tractor beams
- [ ] Missions System
- [ ] Outposts

**Comment by triplezeta** [comment]
:trollface:

**Comment by rye-rice** [comment]
For events i propose the rimworld "bzzt" event and random machines breaking down
