### ISSUE TITLE
To-Do Q3

### ISSUE THREAD

**Issue by MarkSuckerberg** [shiptest-ss13/Shiptest#58]
# Shiptest Q3 To-do list

## Backend

- [x] Fix powernet not regenerating issue #15
- [x] Fix space ruin inability to throw issue #22 
- [x] Remove/rework shuttle IDs
- [x] Ability to spawn ships without serious admin intervention
- [x] Remove is_station_level and other such unecessary/broken defines #215

## Frontend

- [x] Remove access requirements on APCs, Air Alarms, &c... #64 
- [x] Add a way to end rounds IC #65
- [x] Remove emergency/arrrivals/&c static shuttles
- [x] Give ships per-ship features, such as a bank account for each ship
- [x] Add jobs per ship
- [x] ~~Rebalance events?~~
- [x] ~~Add simple round objective goals~~

**Comment by ZephyrTFA** [comment]
pog
